<?php
	define( 'JAJ_ERROR_NEWSLETTER_OK', 0 );
	define( 'JAJ_ERROR_NEWSLETTER_CONVERT_FAIL', 1 );
	define( 'JAJ_ERROR_NEWSLETTER_SEND_FAIL', 2 );
	define( 'JAJ_ERROR_NEWSLETTER_PREVIEW_EMAIL_MISSING', 3 );
	define( 'JAJ_ERROR_NEWSLETTER_EMPTY_SUBSCRIPTION_LISTS', 4 );
?>
