{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
<div class="block">
  <table class="list" cellspacing="0">
  <tr>
      <td>
          <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" size="10" name="{$attribute_base}_data_text_{$attribute.id}" value="{$attribute.content.email|wash(xhtml)}" />
      </td>
      <td>
        <input class="button" type="submit" name="CustomActionButton[{$attribute.id}_send_preview]" value="{'Send preview'|i18n('extension/jajnewsletter/datatype' )}" />
      </td>
      <td>
        {$attribute.content.status|wash(xhtml)}
      </td>
  </tr>
  </table>
  {$attribute.content|attribute(show)}
  {$attribute.data_text|wash(xhtml)}
</div>
{/default}